title: Blog
description: A Blog documenting the development progress of Cantinas.pt.
hero_subheading:
baseurl: ""
url: "https://blog.cantinas.pt"
lang: en
timezone: UTC
markdown: kramdown
theme: null
plugins:
  - jekyll-feed

collections:
  posts:
    output: true

permalink: /:categories/:year/:month/:day/:title/

home_posts_limit: 4

nav_links:
  - label: Home
    url: /
  - label: Cantinas.pt
    url: https://cantinas.pt
  - label: GitHub
    url: https://github.com/joaonunovalente/cantinas

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      image: /assets/images/posts/monitor-icon-alt.svg

exclude:
  - vendor
  - node_modules
  - README_drafts
